-- Properties where average rating is >= 4.0
SELECT
	P.NAME AS "Property Name",
	ROUND(AVG(R.RATING), 2) AS "Average Rating"
FROM
	PROPERTY P
	INNER JOIN REVIEW R ON R.PROPERTY_ID = P.PROPERTY_ID
WHERE
	(
		SELECT
			AVG(R.RATING) AS "Average Rating"
		FROM
			REVIEW R
		WHERE
			R.PROPERTY_ID = P.PROPERTY_ID
	) >= 4
GROUP BY
	P.NAME
ORDER BY
	"Average Rating" DESC;

-- Users with more than 3 bookings
SELECT
	U.FIRST_NAME,
	COUNT(*)
FROM
	BOOKING B
	INNER JOIN USERS U ON U.USER_ID = B.USER_ID
WHERE
	(
		SELECT
			COUNT(*)
		FROM
			BOOKING B
		WHERE
			B.USER_ID = U.USER_ID
	) >= 4
GROUP BY
	U.FIRST_NAME
ORDER BY
	COUNT DESC;